<template>
  <div>
    <div class="bg-black text-white">
        <div class="fixed top-0 left-0 right-0 z-40 h-16">
        </div>
        <div class="top-0 left-0 right-0">
          <div class="w-[1224px] m-auto max-w-full">
            <div class="mt-16 px-4 w-full">
              <h2 class="pt-8 pb-4 heading">Legal Notice</h2>
              <h3 class="pt-8 pb-4 heading2">R GmbH</h3>
              <p>Wollzeile 11</p>
              <p>1010 Vienna</p>
              <p>AUSTRIA</p>
              <p>office@r.com</p>
              <p>UID: ATU79170218</p>
              <p>Firmenbuch: FN 1108534 g</p>
              <p>Gerichtsstand: Wien</p>
              <h3 class="pt-8 pb-4 heading2" >Legal notice</h3>
              <p>All rights reserved. Downloading, printing and saving files from this website is permitted for private
                use
                only. Any other use, in particular the creation of a hyperlink or framing on or with regard to parts of
                this
                website requires the prior written consent of dotsandlines GmbH. Any content of the website and its
                parts has
                been created and monitored with the greatest possible care. Any liability with regard to links to other
                websites and the correctness and up-to-dateness of the information contained therein, as well as for
                data loss
                or other technical impairments that may occur when viewing or downloading data from this website, is
                excluded.</p>
              <h3 class="pt-8 pb-4 heading2">Copyright</h3>
              <p>Designs, graphics, texts, pictures, sound, animations and videos as well as their arrangement on the
                webpage
                of dotsandlines GmbH are subject to copyright protection and other protective laws. The content of this
                website may not be copied, distributed, modified or made available to third parties for commercial
                purposes.
                No part of the site may be reproduced in any form or processed, duplicated or otherwise distributed
                using
                electronic systems without written permission.</p>
              <p>We would like to point out that some of the images contained on the website are subject to the
                copyright of
                third parties.</p>
              <p>All information on these pages is provided without guarantee for its correctness. In no event will we
                be
                liable for any damages resulting from the use of the retrieved information.</p>
              <h3 class="pt-8 pb-4 heading2">Web analysis with Google Analytics</h3>
              <p>This website uses Google Analytics, a web analytics service provided by Google, Inc (&quot;Google&quot;).
                Google Analytics uses &quot;cookies&quot;, which are text files placed on your computer, to help the
                website
                analyze how users use the site. The information generated by the cookie about your use of this website
                is
                usually transmitted to a Google server in the USA and stored there. In the event that IP anonymization
                is
                activated on this website, however, your IP address will be truncated beforehand by Google within member
                states of the European Union or in other contracting states to the Agreement on the European Economic
                Area.
                Only in exceptional cases will the full IP address be transmitted to a Google server in the USA and
                shortened
                there. On behalf of the operator of this website, Google will use this information for the purpose of
                evaluating your use of the website, compiling reports on website activity and providing other services
                relating to website activity and internet usage to the website operator. The IP address transmitted by
                your
                browser as part of Google Analytics will not be merged with other data from Google. You may refuse the
                use of
                cookies by selecting the appropriate settings on your browser, however please note that if you do this
                you may
                not be able to use the full functionality of this website.</p>
              <h3 class="pt-8 pb-4 heading2">Environment</h3>
              <p>The current environment is: <!-- -->production</p>
              <p> The current branch is: <!-- -->main</p></div>
            <div class="flex flex-col items-start pt-16 mx-4">
              <div class="w-[36px] py-3">
                <div class="lf-player-container">
                  <div id="lottie" style="background:transparent;margin:0 auto;outline:none;overflow:hidden"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
    <Footer/>
  </div>
</template>

<style>
.heading{
  font-size: 40px;
  line-height: 36px;
  font-weight: bold;
}

.heading2{
  font-size: 36px;
}
</style>

<script>
import Footer from '../components/footer';

export default {
  components: {
    Footer,
  },
}
</script>
