<template>
  <div>
    <div class="bg-black text-white">
      <div class="fixed top-0 left-0 right-0 z-40 h-16">
      </div>
      <div class="top-0 left-0 right-0">
        <div class="w-[1224px] m-auto max-w-full">
          <div class="mt-16 px-4 w-full">
            <h2 class="pt-8 pb-4 heading">Privacy Policy</h2><br>
            <p>Last updated: November 30, 2022</p><br>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
              information when You use the Service and tells You about Your privacy rights and how the law protects
              You.</p><br>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
              collection and use of information in accordance with this Privacy Policy.</p>

            <h2 class="pt-8 pb-4 heading">Interpretation and Definitions</h2>
            <h3 class="pt-8 pb-4 heading2">Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following
              conditions. The following definitions shall have the same meaning regardless of whether they appear in
              singular or in plural.</p>

            <h3 class="pt-8 pb-4 heading2">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p><br>

            <ul>
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <br>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Real
                Estate AVM GmbH , Wollzeile 11, 1010 Vienna.
              </li>
              <br>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a
                website, containing the details of Your browsing history on that website among its many uses.
              </li>
              <br>
              <li><strong>Country</strong> refers to: Austria</li>
              <br>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital
                tablet.
              </li>
              <br>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <br>
              <li><strong>Service</strong> refers to the Website.</li>
              <br>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the Company to facilitate the Service, to
                provide the Service on behalf of the Company, to perform services related to the Service or to assist
                the Company in analyzing how the Service is used.
              </li>
              <br>
              <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a
                User can log in or create an account to use the Service.
              </li>
              <br>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from
                the Service infrastructure itself (for example, the duration of a page visit).
              </li>
              <br>
              <li><strong>Website</strong> refers to RealEstateAVM, accessible from www.realestateavm.com</li>
              <br>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on
                behalf of which such individual is accessing or using the Service, as applicable.
              </li>
              <br>
            </ul>

            <h2 class="pt-8 pb-4 heading">Collecting and Using Your Personal Data</h2>
            <h3 class="pt-8 heading2">Types of Data Collected</h3>
            <h4 class="pt-8 pb-4 heading3">Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p><br>
            <ul>
              <li>Email address</li><br>
              <li>First name and last name</li><br>
              <li>Phone number</li><br>
              <li>Address, State, Province, ZIP/Postal code, City</li><br>
              <li>Usage Data</li><br>
            </ul>

            <h4 class="pt-8 pb-4 heading3">Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p><br>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <h4 class="pt-8 pb-4 heading3">Information from Third-Party Social Media Services</h4>
            <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p><br>
            <ul>
              <li>Google</li><br>
              <li>Facebook</li><br>
              <li>Twitter</li><br>
              <li>LinkedIn</li><br>
            </ul>
            <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
            <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
            <h4 class="pt-8 pb-4 heading3">Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <ul>
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li><br>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li><br>
            </ul>
            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.</p><br>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p><br>

            <ul>
              <li><strong>Necessary / Essential Cookies</strong><br><br>Type: Session Cookies<br><br>Administered by: Us<br><br>
                Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li><br>

              <li><strong>Cookies Policy / Notice Acceptance Cookies</strong><br><br>Type: Persistent Cookies<br><br>Administered by: Us<br><br>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li><br>

              <li><strong>Functionality Cookies</strong><br><br>Type: Persistent Cookies<br><br>Administered by: Us<br><br>
                Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li><br>
            </ul>
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p><br>

            <h3 class="pt-8 heading2">Use of Your Personal Data</h3>
            <!-- TEXT -->

          </div>
        </div>
      </div>
    </div>
    <Footer/>
  </div>
</template>

<style>
.heading {
  font-size: 40px;
  line-height: 36px;
  font-weight: bold;
}

.heading2 {
  font-size: 36px;
}

.heading3 {
  font-size: 28px;
}

ul li {
  /*
   * We want the bullets outside of the list,
   * so the text is aligned. Now the actual bullet
   * is outside of the list’s container
   */
  list-style-position: outside;

  /*
   * Because the bullet is outside of the list’s
   * container, indent the list entirely
   */
  margin-left: 1em;
}

ul li::before {
  content: "\2022";
  color: white;
  font-weight: bold;
  display: inline-block;
  width: 1em;
  margin-left: -1em;
  font-size:25px;
}

</style>

<script>
import Footer from '../components/footer';

export default {
  components: {
    Footer,
  },
}
</script>
